# Site settings
title: Pete Astor
email: peteastor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Pete Astor, formerly of The Loft and The Weather Prophets, writes, sings songs and teaches music. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://emmawinston.github.io/pete-astor" # the base hostname & protocol for your site
twitter_username: peteastor
# Build settings
markdown: kramdown
